default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: Sched_development

test:
  <<: *default
  database: Sched_test

production:
  <<: *default
  database: Sched_production
  username: Sched
  password: <%= ENV['SCHED_DATABASE_PASSWORD'] %>
